{% set version = "5.2.0" %}
{% set sha256 = "7427d4b63861c1896865ea7be078fa1e2b219ce9b1a9a0895f823475a5f76c85" %}

package:
    name: testfixtures
    version: {{ version }}

source:
    fn: testfixtures-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - testfixtures
        - testfixtures.tests
        - testfixtures.tests.test_django

about:
    home: http://pythonhosted.org/testfixtures/
    license: MIT
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io/en/latest/
    dev_url: https://github.com/Simplistix/testfixtures

extra:
    recipe-maintainers:
        - ChrisBarker-NOAA
        - JamesMakela-NOAA
