{% set version = "5.4.0" %}

package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: 338aed9695c432b7c9b8a271dabb521e3e7e2c96b11f7b4e60552f1c8408a8f0

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
    home: http://pythonhosted.org/testfixtures/
    license: MIT
    license_file: LICENSE.txt
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io/en/latest/
    dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
