# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "U/lkJA4qeN+dAIK8C/eoC988zxLos5ygPDwBipsxUpEcrZBfmy8+3UKP74pGklLcJPVPYZJGzu/KAt5+orFXmlx6Zz8q/TzHyHSIoPdexPVWfXgA1SEVhqvoqKtl7GgD2RKayk5tKVUmaufbJkGti/RaOlSXxy468m1Z8KPcWGyHxRCY7LQyNe9C+1pFAFCxWs1qPfAeie0Q6tQ8hKRSzW0MpTdNPe+WHuBSj3yJKGj1O7UfFDuGJVzaVkebbE2XjRenn6TBZVyydvJQoNhOw84zx6YXew7SByggfgwBb4sXWf/bcdNB2KK6slLFY9s4Kg6QTIuC10aA1VU5LD7q7V2mG0QqyTkvC4EmVCt60i08eQ5myOjU6exDqrgnBMJ8c0VxBvdENPHjLLPwQpPGD1M+ToST4x6YUeP8fHDeqLksIOQUimVQQyPRqhe+urGvsZSWGO0oeyprvmVhLwqr0HWhC3htV4K+sZV0b6M7mQxesHaM2k3vlWxaLFabytL+l1B5ByXYGOtAVXG/9ibxdTENPdfruQ3Wb5/kLWN3ColYhZC5jD84IbFUBFESRjo/U+3H8QSikUwBL4qh28uT6ffm91n2vuZQusj5M8Y/ezZCyDXQFjP4TvLKQCw1x2+b/J/gA+mT24KDbUL6DKEngotwFEke1G+yA5PzD/CfLLw="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
