travis:
  secure:
    BINSTAR_TOKEN: yf7qLgLy0xiWD9OzTIflHSZkn4TPv7+XuTCQVXBMXvgCeZsIxH6uxecg7j+vZaiHwBaQJGoIyWzjk+sGhm8Dr2NimkSNF2KcJFrBsv4HcPzPn/pTnUkwMmpjFIYsovTBLmAqq81IoKLVOzgtNnTKdUWyhvFtnVW72OgOFwALtc6LuzDgbO5io0tdUUBXaZoF7uK4YoJF9X1mcma5M12hP/qedyR8aKvm2qp7NAMhnWhhNN/kE9vrmkAE1YmHJzabK7OPBMVmUTvYhQk991YJSqxuCnPtKary10hEjd4YV0fWRXpyeMgIps3BhjjSO8x5FNme9JLqlrcpTiik2fNvmuLwiyClo8P6a8RJe0jhyFLKQimgMQkB9vfOa+5WF3fHZ3h7q8qfxMOEuFk8Bdx0dLUF9Bz/hEFgjg7gwqlY9bT/WZbdjw8qTUSbcCbPETQ8tyOVdLjZRMX/hMHsIMmhy4iC/GPOw6SiALVkuLLRJJJPGbhnP7V/65tkOOn20vOAe4eLgvFChf+IeiNoTq5S/LL6Go7dkDUJHmoaYkZHBiYUMd82fRFS7wojcfKV2mrnwiO9vewgV50K9HyxOrKURH2cXZDeIqlnIHt2zkdV6fus0KzF06UpX3VfFtfZPSMNqGi8q6rk99Z8Lnmuobz+lg717z7ZwKIXlXpTFxqqIqA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
