travis:
  secure:
    BINSTAR_TOKEN: nAAyf9ACiVR1Hwf5pIRDI4Ua0E84ORqoMmzA28KzRF2OVgvh5pQ7IBRvitUJ6NYkoZdpwEgjeuyPrrV5agH9Rj19eMOWfA/LwzeVFW+rH5njrQoKr5FmbVpRGh2zY318XCCqhkJHY1A4IyVwetGjqdjOlPMV999n8R6uhfZy6n8q++1I4wBNXPC5NI09ZzYHen1TuvDd83SH9GM62RlgMEg66dxBQAw19uKsBpgm9ktiVt1pIpKXHgXm00ezfiRSYjgPOCYRj7XlIue70fi3SBSGWrIZNvh7EQ/ajC9ZBEqfZ0480XK6GEPdPGmHHSVACMJnAls+bjms7qzkBR4aUxmp9Ij3k9IarrASGLFqdfHlNrAPJHgw9RqINQ0xUdzc6X1QE6zTJ6eBm/xvjVldGzpM/xey88PKMskD+v9fABrCSNknulEAOrQ3I3Jem+Lia9BSxFUEq/M8wDmdXaPNnxwdeWRuk0lsNIQvcXRtcg1P5zpXRy3Vq5oz/ur9d+x1YYgXxoYGdI1xpuIkE0fkf9gflG7UNrndgbp9L4kjcMwYfMKnMwSpI/4/bT+rKgrY++/LRPOsfQvhRDHDunwNecgqsoXy84jDWICG5LUII66bgtg24JmeaxPru3JpopfERQor30vZCPpKlsD4kMWB8IxxQ7soKYrInTO3FEIIfgk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
