travis:
  secure:
    BINSTAR_TOKEN: JjWhXIWwDcQPsmIS92K5RUqmJWJZB2ZAA7Gf4Cxfci/hi1A590cnBLd+fnXi2CfWZlvPe/umqYYE9UwDwIgmY8SFZLkSt9MaxI/vo8xb6dX/Y+/+RgxlTImVl0dMjoEjwwTuysf52+N0u7hdEvDUVzyxzVswegu3OnQJ4T24HqQyIQAatWmrRmXHPxAU/VOtLdF9esrwcX+f0LCAM2xqQ/pnfm5HYI3UTJSEmSFS413ABvPoY1oFNo8kCwK+A9RJ2Gcd9hw9lirppYbwCNVKo1FfD/kQZp1Lftf3UeAjdfzdtJxahkLmCVcKk0V5xfGIris4WwJrnEFX3RKpC4FfuJ56kkSf67da6K6ndMEBgZ0ZI5GrapEkUUL0+nYGyvVdvluKI4SHaeR4EM4U93xzfp9OhnJ4V7nSBIB0jGdUNKJQsxjDb0myToGPIys2CCPBKNvLY2fIpyrdP4WrYRpx3ZZsPt3n7Ni0xa2bX9s0VyTSdBk4cf7aI9MAh3toSi7JiQciOUL1scVlw+bUxnjylSbShFEr/C0pmYWMz0prRBZpKexUV4fxyZLJcRCDZSi0M/jQ4eVFl9P+Iq18Gvidqw5hBXqC08NdktAzgEumt7p7hH84yem4O0YKDD8SEhMjA4P8bIAu3GpIjT+J9r9xju0QLRoHMYoQzokchIzlO+k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
