travis:
  secure:
    BINSTAR_TOKEN: U/lkJA4qeN+dAIK8C/eoC988zxLos5ygPDwBipsxUpEcrZBfmy8+3UKP74pGklLcJPVPYZJGzu/KAt5+orFXmlx6Zz8q/TzHyHSIoPdexPVWfXgA1SEVhqvoqKtl7GgD2RKayk5tKVUmaufbJkGti/RaOlSXxy468m1Z8KPcWGyHxRCY7LQyNe9C+1pFAFCxWs1qPfAeie0Q6tQ8hKRSzW0MpTdNPe+WHuBSj3yJKGj1O7UfFDuGJVzaVkebbE2XjRenn6TBZVyydvJQoNhOw84zx6YXew7SByggfgwBb4sXWf/bcdNB2KK6slLFY9s4Kg6QTIuC10aA1VU5LD7q7V2mG0QqyTkvC4EmVCt60i08eQ5myOjU6exDqrgnBMJ8c0VxBvdENPHjLLPwQpPGD1M+ToST4x6YUeP8fHDeqLksIOQUimVQQyPRqhe+urGvsZSWGO0oeyprvmVhLwqr0HWhC3htV4K+sZV0b6M7mQxesHaM2k3vlWxaLFabytL+l1B5ByXYGOtAVXG/9ibxdTENPdfruQ3Wb5/kLWN3ColYhZC5jD84IbFUBFESRjo/U+3H8QSikUwBL4qh28uT6ffm91n2vuZQusj5M8Y/ezZCyDXQFjP4TvLKQCw1x2+b/J/gA+mT24KDbUL6DKEngotwFEke1G+yA5PzD/CfLLw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
